fix getProductName regex (run-ios)
react-native-community/cli pull request #1314
Opened 2020-11-16 22:21 UTC by immackay

Summary:
---------

`getProductName` used in the `run-ios` command from `cli-platform-ios` was failing to correctly parse build output and instead only returned the scheme name passed. It seems that the build output has a backslash before all equals signs, so this change reflects that.

Test Plan:
----------

Run `react-native run-ios` with a scheme name different from the CFBundleIdentifier.

2020-11-18 12:09 UTC, thymikee requested changes
Can you add a test or at least a video/screenshot of when it happens and how this change fixes it? :)

2020-11-18 12:09 UTC, thymikee commented on packages/platform-ios/src/commands/runIOS/index.ts
> +  const productNameMatch = /export FULL_PRODUCT_NAME\\="?(.+).app"?$/m.exec(
Can you make this backslash optional? The regex worked earlier, so that's probably some recent change.

2020-11-23 20:29 UTC, grabbou commented
Reproduced, got the error with custom scheme name:

> xcodebuild: error: The workspace named "RNTestProject" does not contain a scheme named "RNTestProject". The "-list" option can be used to find the names of the schemes in the workspace.

The scheme name I set was `RNTestProjectTestSchemeName`. Looking into it.

2020-11-23 20:41 UTC, grabbou commented
I am going to close this PR and send a follow up PR that refactors this entire code. Looking for `appName` is not necessary and relying on it to detect tvOS is a bit brittle. 

Will cross-link. Thank you for raising our awareness on this.

2020-11-23 20:41 UTC, closed without merging