fix(platform-ios): detect Podfile and .xcworkspace
react-native-community/cli pull request #1436
Opened 2021-06-28 13:00 UTC by tido64

Summary:
---------

`react-native config` fails to recognize projects that contain only a Podfile or `.xcworkspace`, e.g. because the Xcode project is generated. This change makes it output a config if either are found.

Resolves #1435
Resolves the iOS part of #1054

Test Plan:
----------

```
git clone git@github.com:react-native-menu/menu.git
cd menu
mv example/ example2/ # This is to just move the existing test app out of the way temporarily
yarn add react-native-test-app --dev
yarn init-test-app
# The options I chose
# ✔ What is the name of your test app? … MenuExample
# ✔ Which platforms do you need test apps for? › Android, iOS
# ✔ Where should we create the new project? … example

cd example
yarn
yarn link "@react-native-community/cli"
yarn link "@react-native-community/cli-platform-ios"
pod install --project-directory=ios
yarn ios
```

2021-06-28 15:40 UTC, thymikee approved these changes
LGTM. What do you think @grabbou?

2021-07-05 19:03 UTC, tido64 commented
@grabbou, @Esemesek: Gentle ping. Let me know if you have any comments and I'll try to address them. 😄

2021-07-06 12:02 UTC, grabbou requested changes
Thanks for the PR. I left a series of comments.

Before going to addressing them, I wanted to better understand the nature of this PR. 

In what scenario, an `xcworkspace` will be present, but `xcodeproj` not?

Why should we allow CLI to detect projects that don't have `.xcworkspace` and `.xcodeproj`, but have a `Podfile` only? CLI is designed to support projects, not dependencies.

2021-07-06 12:20 UTC, thymikee commented on packages/platform-ios/src/config/index.ts
> +    podfile: podfile && path.resolve(podfile),
Hm right, with `!project && !podfile` guard we don't need to check either of those

2021-07-06 12:37 UTC, grabbou commented
@tido64 how about we hop on a call at some point this or next week to discuss this?

2021-07-06 12:42 UTC, tido64 commented
> In what scenario, an `xcworkspace` will be present, but `xcodeproj` not?
> 
> Why should we allow CLI to detect projects that don't have `.xcworkspace` and `.xcodeproj`, but have a `Podfile` only? CLI is designed to support projects, not dependencies.

I filed a feature request on this last year or so here: https://github.com/react-native-community/cli/issues/1054.

Technically, only `Podfile` and `.xcworkspace` need to reside in the same folder. `.xcworkspace` can point to a `.xcodeproj` anywhere in the file system and does not have the same restriction. Moreover, if you're using a project generator, you may not find a `.xcworkspace` there at all.

A more specific example are projects using [`react-native-test-app`](https://github.com/microsoft/react-native-test-app) to generate both `.xcworkspace` and `.xcodeproj` during `pod install` (there was an [RFC](https://github.com/react-native-community/discussions-and-proposals/pull/204) some time back if you're interested in details). Such projects may only have a `Podfile` in the `ios` folder ([example](https://github.com/react-native-async-storage/async-storage/tree/master/example/ios), [example 2](https://github.com/react-native-menu/menu/pull/142)). The generated `.xcodeproj` is hidden since it's managed by `react-native-test-app` and is not meant to be checked in. This is to hide away a piece of complexity that users need not care about. This is especially beneficial when they need to upgrade (or downgrade) `react-native`.

2021-07-06 12:45 UTC, tido64 commented
> @tido64 how about we hop on a call at some point this or next week to discuss this?

Yes, we can do that as well. I know you're super busy so let me know when you have time?

2021-07-06 12:51 UTC, grabbou commented
I will reach out to you directly over Discord and we will send a note when we're done

2021-08-04 21:08 UTC, closed without merging