feat: Allow the upgrade command to support the TV repo
react-native-community/cli pull request #1477
Opened 2021-09-28 20:23 UTC by douglowder

Summary:
---------

The upgrade command does not currently work for Apple TV and Android TV projects, because they use `react-native-tvos`, a fork of the main repo.

Solution:
- Provide a version of https://github.com/react-native-community/rn-diff-purge that has the diffs for the TV repo
- Make `upgrade.ts` generic by detecting whether the project is using a forked repo, and having an easily extendable list of forks that are known to work.  This list includes the main repo as well.

```ts
type ForkNameType = 'react-native' | 'react-native-tvos';

const forks = {
  'react-native': {
    rawDiffUrl:
      'https://raw.githubusercontent.com/react-native-community/rn-diff-purge/diffs/diffs',
    webDiffUrl: 'https://react-native-community.github.io/upgrade-helper',
    dependencyName: 'react-native',
  },
  'react-native-tvos': {
    rawDiffUrl:
      'https://raw.githubusercontent.com/react-native-tvos/rn-diff-purge-tv/diffs/diffs',
    webDiffUrl: 'https://react-native-community.github.io/upgrade-helper',
    dependencyName: 'react-native@npm:react-native-tvos',
  },
};

```

All methods in `upgrade.ts` now refer to this structure in their implementations.

Test Plan:
----------

- I duplicated all the existing unit tests for `upgrade.ts` in a separate `upgrade-tv.test.ts` file so that all tests run against the TV repo
- I tested manually with a project generated with an older version of `react-native-tvos`

2021-09-29 18:39 UTC, thymikee requested changes
Thanks for submitting a PR! I have 2 pieces of feedback:
- consider using "repo" name instead of "fork", seems more appropriate
- is there a possibility we could somehow generate the test for tvos? e.g. reading the upgrade.test.ts through `fs` API, search/replace specific phrases and eval it? would ease maintenance. But if it proves to be too problematic, we can leave it as is

2021-09-29 19:00 UTC, douglowder commented
@thymikee I'll take a look at consolidating the test, and I'll make the change to "repo" instead of "fork".

Do you know why the azure-pipelines PR check failed?

2021-09-29 19:01 UTC, thymikee commented
> Do you know why the azure-pipelines PR check failed?

It fails for a good while now. Didn't bother to check what's actually causing the failure. You don't need to be worried about it.

2021-10-02 20:37 UTC, douglowder commented
@thymikee this is ready for review again -- I moved all the upgrade test imports and implementations to a common file used by both react-native and react-native-tvos tests.

2021-10-03 23:02 UTC, douglowder commented
Looks like something I did caused linting to break -- will close this and open a new PR once I check everything

2021-10-03 23:02 UTC, closed without merging