feat: check if configuration for iOS project exists
react-native-community/cli pull request #1810
Opened 2023-01-26 11:45 UTC by TMisiukiewicz

Summary:
---------

When running `run-ios` or `build-ios` command with `--mode` option, throw error if the configuration does not exist in the project.

Test Plan:
----------

1. Use `run-ios --mode Release` - should run correctly
2. Use `run-ios --mode Test` - should throw an error
3. Use `build-ios --mode Release` - should run correctly
4. Use `build-ios --mode Test` - should throw an error

2023-01-26 15:56 UTC, adamTrz approved these changes
LGTM 👍

2023-01-27 07:15 UTC, szymonrybczak approved these changes
Good job! 💪

2023-01-27 08:35 UTC, thymikee commented on packages/cli-platform-ios/src/tools/getProjectInfo.ts
> +  process.chdir('./ios');
this is assuming we know where the ios folder is, which may not always be true, e.g. in monorepos. You should be able to use `config.platform.ios.sourceDir` instead

2023-01-27 08:36 UTC, thymikee commented on packages/cli-platform-ios/src/commands/runIOS/index.ts
> +  const projectInfo = getProjectInfo();
You can pass the `sourceDir` from here

2023-01-27 08:37 UTC, thymikee requested changes
I'd appreciate a test for that

2023-01-27 13:18 UTC, TMisiukiewicz commented
updated `projectInfo` function and added tests

2023-01-27 14:21 UTC, thymikee approved these changes

2023-01-27 14:50 UTC, merged