chore (doctor): update Node minimum version to 18
react-native-community/cli pull request #1986
Opened 2023-06-26 06:14 UTC by Shubham1429

Summary:
---------

Set minimum Node version to 18.

Part of https://github.com/react-native-community/cli/issues/1936

2023-07-04 15:54 UTC, szymonrybczak requested changes
Thanks! You need also to change node version in the `engines` in `package.json`, see here: https://github.com/react-native-community/cli/blob/5d8a8478cd104adf4a4dd34c09c2e256325ae61d/packages/cli/package.json#L20-L22
also `@types/node` in few packages,  in `babel.config.js` and in `.github/workflows/test.yml` just leave Node 18 for running unit tests.

2023-07-11 16:11 UTC, thymikee commented
@Shubham1429 can you rebase and address the feedback? :)

2023-07-17 06:49 UTC, szymonrybczak approved these changes
Thanks! 🎉

2023-07-17 10:57 UTC, cortinico approved these changes

2023-07-17 11:16 UTC, merged