feat: enable pausing handling keystrokes in watch mode
react-native-community/cli pull request #2041
Opened 2023-08-01 15:17 UTC by szymonrybczak

Summary:
---------

In this PR I created `KeyPressHandler` that allows us to pause handling keystrokes because in nearest future we will add interactive prompts to `start` command, so they will run in watch mode. If we do not pause the handling keystrokes, the "focus" will be on the prompt. I created a function that wraps `prompts` and pauses and resumes interactivity in watchMode. 

Test Plan:
----------

1. Clone the repository and do all the required steps from the [Contributing guide](https://github.com/react-native-community/cli/blob/main/CONTRIBUTING.md)
2. Run this command:

```sh
node /path/to/react-native-cli/packages/cli/build/bin.js start
```
3. Press key that we're handling (`a`,` i`, `d`, `r`) and check if keystrokes are properly handled. 
 

Checklist
----------

- [x] Documentation is up to date to reflect these changes.
- [x] Follows commit message convention described in [CONTRIBUTING.md](https://github.com/react-native-community/cli/blob/main/CONTRIBUTING.md#commit-message-convention)

2023-08-09 17:59 UTC, thymikee commented on packages/cli-plugin-metro/src/tools/KeyPressHandler.ts
> +  constructor(public onPress: (key: string) => Promise<any>) {}
I think we're don't intend to return anything from this fn and if it must be either sync or async, let's state that in the type
```suggestion
  constructor(public onPress: (key: string) => Promise<void> | void) {}
```

2023-08-09 17:59 UTC, szymonrybczak commented on packages/cli-plugin-metro/src/commands/start/watchMode.ts
> +  const onPressAsync = async (key: string) => {
we're awaiting it here: 
https://github.com/react-native-community/cli/blob/e8f7148c5d6ca71acf65b62848f05be5321f0d88/packages/cli-plugin-metro/src/tools/KeyPressHandler.ts#L40

2023-08-09 18:03 UTC, thymikee commented on packages/cli-plugin-metro/src/tools/KeyPressHandler.ts
> +      return new CLIError('There was an error with the key press handler.');
we should pass the `error` to CLIError to get user some context. This is execa that can fail here right? Let's make sure the output is readable

2023-08-09 18:12 UTC, thymikee commented on packages/cli-plugin-metro/src/commands/start/watchMode.ts
> +  addInteractionListener(listener);
would it be a bad idea to move this call to `createInteractionListener()`?

2023-08-09 18:23 UTC, thymikee commented on packages/cli-plugin-metro/src/commands/start/watchMode.ts
> +  const onPressAsync = async (key: string) => {
yup, however there's no async code inside this fn so there's no point in doing that now. if the handler body becomes async, we could extend the listener type then

2023-08-09 18:37 UTC, thymikee commented on packages/cli-plugin-metro/src/tools/KeyPressHandler.ts
> +      await this.onPress(key);
when this gets sync (which it is right now in fact), `this.isHandlingKeyPress` gets unnecessary

2023-08-09 18:56 UTC, thymikee requested changes
small nits and this is good to go

2023-08-10 07:51 UTC, szymonrybczak commented on packages/cli-plugin-metro/src/commands/start/watchMode.ts
> +  const onPressAsync = async (key: string) => {
ah, right

2023-08-10 08:06 UTC, thymikee approved these changes

2023-08-10 14:16 UTC, merged