fix: Remove hardcoded npm registry url #2519
react-native-community/cli pull request #2520
Opened 2024-10-06 09:30 UTC by jasonjiicloud

Summary:
---------
fixes: #2519
Official npm registry url is hardcoded, the "cli" can't run successfully in a closed environment.

Following error is displayed when running `npx @react-native-community/cli@latest init AwesomeProject --verbose`.

```
error fetch failed.
TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getTemplateVersion (/Users/jilingyun/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/tools/npm.js:121:16)
    at async createTemplateUri (/Users/jilingyun/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/commands/init/version.js:53:29)
    at async createProject (/Users/jilingyun/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/commands/init/init.js:341:23)
    at async Object.initialize [as func] (/Users/jilingyun/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/commands/init/init.js:422:7)
    at async Command.handleAction (/Users/jilingyun/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/index.js:116:9)
```

My solution is using `getNpmRegistryUrl()` to get real npm registry url in user's local environment, then it can avoid using official npm registry directly.

Test Plan:
----------

Build and run `node /path/to/react-native-cli/packages/cli/build/bin.js init AwesomeProject`

Checklist
----------

- [ ] Documentation is up to date to reflect these changes.
- [ ] Follows commit message convention described in [CONTRIBUTING.md](https://github.com/react-native-community/cli/blob/main/CONTRIBUTING.md#commit-message-convention)

2024-10-07 10:32 UTC, szymonrybczak commented on packages/cli/src/tools/npm.ts
> +  const json = await fetch(getNpmRegistryUrl() + '@react-native-community/template').then(
I'd prefer leveraging here `new URL()` to make sure URL is always in a correct format, e.g. when `getNpmRegistryUrl()`'d return value without `/` at the end, previous would've fail.

```suggestion
  const json = await fetch(new URL('@react-native-community/template', getNpmRegistryUrl())).then(
```

2024-10-07 10:32 UTC, szymonrybczak approved these changes
Makes a lot of sense, thanks! 👍

2024-10-07 10:32 UTC, szymonrybczak commented
cc @blakef

2024-10-07 10:55 UTC, blakef requested changes
This is a really nice change.  Couple of small things before you land it:
1. update the URL handling to use `URL` as @szymonrybczak  suggested
2. fix the formatting

2025-02-04 04:05 UTC, blakef approved these changes

2025-02-04 04:06 UTC, merged